### ISSUE TITLE
TODO - Implement GET /tasks Endpoint

### ISSUE THREAD

**Issue by rajeshsinha1997** [rajeshsinha1997/task-manager-rest-java#2]
- implement GET /tasks endpoint to fetch all available tasks

**Comment by AlexeyShary** [comment]
Hi!
Can i take this one?

**Comment by rajeshsinha1997** [comment]
Hi @AlexeyShary, Sure! Please create a separate feature branch and implement your changes over there. Once done please create a PR to the existing dev branch and add my name as a reviewer. :)

**Comment by AlexeyShary** [comment]
@rajeshsinha1997 I did it - https://github.com/rajeshsinha1997/task-manager-rest-java/pull/4
But I can't add a reviewer. It seems I don't have the necessary permissions for this.

![image](https://github.com/rajeshsinha1997/task-manager-rest-java/assets/119926093/75857d63-3e45-43c9-909e-22e6481abea0)

**Comment by rajeshsinha1997** [comment]
> @rajeshsinha1997 I did it - https://github.com/rajeshsinha1997/task-manager-rest-java/pull/4
> 
> But I can't add a reviewer. It seems I don't have the necessary permissions for this.
> 
> 
> 
> ![image](https://github.com/rajeshsinha1997/task-manager-rest-java/assets/119926093/75857d63-3e45-43c9-909e-22e6481abea0)
> 
> 

I've taken care of the review part.

**Comment by rajeshsinha1997** [comment]
Thanks, @AlexeyShary for your efforts in implementing the changes. This issue can be closed now.
