### ISSUE TITLE
TODO - Update Existing Test Cases to Improve Coverage

### ISSUE THREAD

**Issue by rajeshsinha1997** [rajeshsinha1997/task-manager-rest-java#30]
**Is your feature request related to a problem? Please describe.**
The existing test cases do not cover the codebase sufficiently.

**Describe the solution you'd like**
Add new test cases to improve the code coverage.

**Comment by albertoLago** [comment]
Hello, I will take care of this issue :)

**Comment by rajeshsinha1997** [comment]
Hi @albertoLago, I've assigned the issue to you, you can start working on it. :)

**Comment by albertoLago** [comment]
Thx!!

**Comment by rajeshsinha1997** [comment]
Hi @albertoLago, could you please hold the updation of the existing test cases or the addition of new test cases? 

I'm working on issue #31, which might add some new changes to the existing implementation, and as a result, we will need to modify the test cases again. So, my suggestion will be you resume your work on updating the test cases once the above-mentioned issue is closed.

**Comment by albertoLago** [comment]
Sure, I'll wait until issue #31 is closed. Thanks for letting me know

**Comment by albertoLago** [comment]
Got it, I'll review the updates and proceed with the test cases.
