### ISSUE TITLE
TODO: Add Unit Tests to Improve Code Coverage

### ISSUE THREAD

**Issue by rajeshsinha1997** [rajeshsinha1997/task-manager-rest-java#8]
- add unit tests for the existing code (JUnit or TestNG)
- code coverage must be greater than or equal to 80%

**Instructions:**
1. Create your separate feature branch for this issue and implement your changes in that feature branch
2. Once you're done with implementing the changes, create a PR to merge your changes into the '**develop**' branch and wait for review
3. Once the PR has been reviewed and all conversations are resolved (if applicable), your PR will be merged into the '**develop**' branch.

**Comment by albertoLago** [comment]
Hello,
Could you please assign it to me?

**Comment by rajeshsinha1997** [comment]
Assigned to you @albertoLago, please create your feature branch and implement your changes there. Once done, please create a pull request to the development branch and wait for reviews before merging.
